version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: note_bd
        ports:
            - 8000:8000
        volumes:
            - .:/var/www
        depends_on:
            - postgres

    postgres:
        image: postgres:15-alpine
        container_name: notes_postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: notes
            POSTGRES_USER: notes
            POSTGRES_PASSWORD: notes
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
